#ifndef TEST_STUB_LIBAVUTIL_PIXFMT_H
#define TEST_STUB_LIBAVUTIL_PIXFMT_H

enum AVPixelFormat
{
    AV_PIX_FMT_NONE = -1,
    AV_PIX_FMT_YUV420P,
    AV_PIX_FMT_NV12,
    AV_PIX_FMT_NV21,
    AV_PIX_FMT_YUV422P,
    AV_PIX_FMT_YUV444P,
    AV_PIX_FMT_RGB24,
    AV_PIX_FMT_RGBA,
    AV_PIX_FMT_BGRA,
};

#endif
